[env]
# Will use a centralized venv if `~/.cache/uv-venvs` exists.  `.venv` otherwise.
UV_PROJECT_ENVIRONMENT = "{{ exec(command='tasks/mise-uv-init.py proj-env', cache_key='proj-env', cache_duration='1h') | trim }}"
_.python.venv.path = '{{ env.UV_PROJECT_ENVIRONMENT }}'


# For the demo-pkg script.  Override in mise.local.toml if needed.
_DEMO_PKG_DPATH = '~/projects/coppy-demo-pkg/'


[tools]
python = "{{ exec(command='tasks/mise-uv-init.py py-ver', cache_key='py-ver', cache_duration='1h') | trim }}"


[task_config]
includes = [
    'tasks',
]


################ TASKS #################
[tasks.demo-pkg]
description = "Update Coppy demo pkg"
# The demo command will usually pick a temporary directory by default.  This instructs it to
# use a fixed path for the demo.  That path should point to a local repo cloned from:
# https://github.com/level12/coppy-demo/
env = { DEMO_PKG_DPATH = '{{ env._DEMO_PKG_DPATH }}' }
run = 'mise demo --update --rm-existing --head --nox'


[tasks.upgrade-deps]
description = 'Upgrade uv and pre-commit dependencies'
run = [
    'uv sync --upgrade',
    'pre-commit autoupdate',
]
