
[env]
################ APP ################

# For the demo-update script.  Override in mise.local.toml if needed.
_DEMO_PKG_DPATH = '~/projects/coppy-demo-pkg/'

[tools]
rumdl = 'latest'

[hooks]
enter = "uv sync"


[settings]
# Have mise get it's Python version from .python-version(s).  We get two other benefits:
# 1) uv, apart from mise, will pick the correct python version, and `uv run` and similar can be used
#   apart from mise.
# 2) GitHub's setup-python action can be directed to the .python-version(s) file
idiomatic_version_file_enable_tools = ["python"]

python.uv_venv_auto = "create|source"


[task_config]
includes = [
    'tasks',
]


################ TASKS #################
[tasks.demo-update]
description = "Update Coppy demo pkg"
# The demo command will usually pick a temporary directory by default.  This instructs it to
# use a fixed path for the demo.  That path should point to a local repo cloned from:
# https://github.com/level12/coppy-demo/
env = { DEMO_PKG_DPATH = '{{ env._DEMO_PKG_DPATH }}' }
run = 'mise run demo-gen --update --rm-existing --head --nox'


[tasks.upgrade-deps]
description = 'Upgrade mise, uv, and prek dependencies'
dir = "{{ config_root }}"
run = [
    'mise lock --bump',
    'uv sync --upgrade',
    'prek auto-update',
]
