name: "uv prep"

inputs:
  python-version-file:
    type: string
    required: false
    default: pyproject.toml
  fetch-depth:
    type: number
    required: false
    default: 1
  token:
    type: string
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Debug token
      shell: bash
      run: |
        echo 'github token:' ${{ github.token }}
        echo 'input token:' ${{ inputs.token }}

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}

    - name: Mark repo as safe for Git
      shell: bash
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # NOTE: use GH's action to install Python b/c uv docs say it will be faster due to caching
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ${{ inputs.python-version-file }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
