name: "uv prep"

inputs:
  python-version-file:
    required: false
    type: string
    default: pyproject.toml

runs:
  using: composite
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Mark repo as safe for Git
      shell: bash
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    # NOTE: use GH's action to install Python b/c uv docs say it will be faster due to caching
    - name: "Set up Python"
      uses: actions/setup-python@$v5
      with:
        python-version-file: ${{ inputs.python-version-file }}

    - name: Install uv
      uses: astral-sh/setup-uv@v6
