name: "nox run"

inputs:
  nox-session:
    required: true
  python-version-file:
    required: false
    type: string
    default: pyproject.toml
  uv-group:
    required: false
    type: string
    default: nox
  token:
    type: string
    required: false
    default: ${{ github.token }}


runs:
  using: composite
  steps:
    - name: Debug token
      shell: bash
      run: |
        echo 'github token:' ${{ github.token }}
        echo 'input token:' ${{ inputs.token }}

    - uses: level12/coppy/gh-actions/uv-prep@main
      with:
        python-version-file: ${{ inputs.python-version-file }}
        token: ${{ inputs.token }}

    - name: Run Nox Session
      shell: bash
      run: |
        uv run --frozen --exact --only-group ${{ inputs.uv-group }} -- nox -s ${{ inputs.nox-session }}
