name: "nox run"

inputs:
  nox-session:
    required: true
  python-version-file:
    required: false
    type: string
    default: pyproject.toml
  uv-group:
    required: false
    type: string
    default: nox


runs:
  using: composite
  steps:
    - uses: level12/coppy/gh-actions/uv-prep@main
      with:
        python-version-file: ${{ inputs.python-version-file }}

    - name: Run Nox Session
      shell: bash
      run: |
        uv run --frozen --only-group ${{ inputs.uv-group }} -- nox -s ${{ inputs.nox-session }}
