#!/usr/bin/env bash
# mise description="Prep/run nox in CI container"
# mise hide=true  # Should only be used by docker/ci scripts, no need to make discoverable.
# Used by:
#  - circleci/config.yml
#  - ci/Dockerfile

set -e
set -o xtrace

# Troubleshooting help
pwd
ls -al
echo $PATH
which python
python --version
whoami

# Prep for and run tests
uv pip install -U uv

# Need to install our own package b/c the tests call `mise run demo` which operates in the context
# of the CI virtualenv (/tmp/copier-py) instead of the nox one (./.nox/tests).
uv pip install -r requirements/ci.txt -e .

# Run tests
nox "$@"
